# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'galary.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
i=0
class Ui_galary(object): 
    def setupUi(self, galary):
        galary.setObjectName("galary")
        galary.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(galary)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.picture = QtWidgets.QLabel(self.centralwidget)
        self.picture.setAutoFillBackground(False)
        self.picture.setText("")
        self.picture.setPixmap(QtGui.QPixmap("sample_pics/"+ str(i)+".jpg"))
        self.picture.setScaledContents(True)
        self.picture.setAlignment(QtCore.Qt.AlignCenter)
        self.picture.setWordWrap(False)
        self.picture.setObjectName("picture")
        self.horizontalLayout_2.addWidget(self.picture)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.prev_bt = QtWidgets.QPushButton(self.centralwidget)
        self.prev_bt.setMinimumSize(QtCore.QSize(0, 23))
        self.prev_bt.setObjectName("prev_bt")
        self.horizontalLayout.addWidget(self.prev_bt)
        self.next_bt = QtWidgets.QPushButton(self.centralwidget)
        self.next_bt.setObjectName("next_bt")
        self.horizontalLayout.addWidget(self.next_bt)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout.setStretch(0, 3)
        galary.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(galary)
        self.statusbar.setObjectName("statusbar")
        galary.setStatusBar(self.statusbar)

        self.retranslateUi(galary)
        QtCore.QMetaObject.connectSlotsByName(galary)

        self.next_bt.clicked.connect(self.next_pic)
        self.prev_bt.clicked.connect(self.prev_pic)

    def retranslateUi(self, galary):
        _translate = QtCore.QCoreApplication.translate
        galary.setWindowTitle(_translate("galary", "MainWindow"))
        self.prev_bt.setText(_translate("galary", "<- Previous"))
        self.next_bt.setText(_translate("galary", "Next ->"))

    def next_pic(self):
        global i
        i = (i+1)%10 
        self.picture.setPixmap(QtGui.QPixmap("sample_pics/"+ str(i)+".jpg"))
    def prev_pic(self):
        global i
        i = (i-1)%10 
        self.picture.setPixmap(QtGui.QPixmap("sample_pics/"+ str(i)+".jpg"))
                                             
        
        

    
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    galary = QtWidgets.QMainWindow()
    ui = Ui_galary()
    ui.setupUi(galary)
    galary.show()
    sys.exit(app.exec_())
